name: CI
on:
  schedule:
    - cron: '30 5 * * *'

  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    # Disable the filter on scheduled runs because we don't want to skip those
    if: github.event_name != 'schedule'
    continue-on-error: true # Makes sure errors won't stop us
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
      # For PRs the path filter check with Github API, so no need to checkout
      # for them.
      - if: github.event_name != 'pull_request'
        name: Checkout
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            src:
              - '**.cfg'
              - '**.nims'
              - '**.nim'
              - '**.nimble'
              - 'tests/**'
              - '.github/workflows/ci.yml'
  build:
    # Build if the files we care about are changed.
    needs: changes
    # Make sure to always run regardless of whether the filter success or not.
    # When the filter fails there won't be an output, so checking for `false`
    # state is better than checking for `true`.
    #
    # The always() function here is required for the job to always run despite
    # what Github docs said, see: https://github.com/actions/runner/issues/491
    if: always() && needs.changes.outputs.src != 'false'

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        compiler:
          - name: nim
            version: version-2-0
          - name: nimskull
            version: "*"

    name: '${{ matrix.os }} (${{ matrix.compiler.name }} ${{ matrix.compiler.version }})'
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash
        working-directory: project

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: project

      - name: Nim
        if: matrix.compiler.name == 'nim'
        uses: alaviss/setup-nim@0.1.1
        with:
          path: nim
          version: ${{ matrix.compiler.version }}

      - name: Nimskull
        id: nimskull
        if: matrix.compiler.name == 'nimskull'
        uses: nim-works/setup-nimskull@0.1.2
        with:
          nimskull-version: ${{ matrix.compiler.version }}

      - name: Fetch Nimble
        if: matrix.compiler.name == 'nimskull'
        uses: actions/checkout@v4.1.1
        with:
          path: nimble
          repository: alaviss/nimble
          ref: nimskull

      - name: Build Nimble
        if: matrix.compiler.name == 'nimskull'
        run: |
          nim c -d:release -o:"$NIMSKULL_BIN/nimble" src/nimble.nim
          # Add nimble binary folder to PATH
          echo "$HOME/.nimble/bin" >> "$GITHUB_PATH"
        working-directory: nimble
        env:
          NIMSKULL_BIN: ${{ steps.nimskull.outputs.bin-path }}

      - name: Dependencies
        run: |
          nimble --accept install "https://github.com/nim-works/cps"
          nimble --accept install "https://github.com/disruptek/balls"
          nimble --accept develop

      - name: Tests (gcc)
        run: |
          balls --path="." --cc:gcc --gc:arc --backend:c --define:danger --define:release

      - name: Tests (clang)
        run: |
          balls --path="." --cc:clang --gc:arc --backend:c --define:danger --define:release

      - name: Build docs
        if: ${{ matrix.docs }} == 'true'
        run: |
          branch=${{ github.ref }}
          branch=${branch##*/}
          nimble doc --project --outdir:docs --path="." \
            '--git.url:https://github.com/${{ github.repository }}' \
            '--git.commit:${{ github.sha }}' \
            "--git.devel:$branch" \
            loony.nim
          # Ignore failures for older Nim
          nim doc --outdir:docs --path="." \
            '--git.url:https://github.com/${{ github.repository }}' \
            '--git.commit:${{ github.sha }}' \
            "--git.devel:$branch" \
            loony/ward.nim
          cp docs/{the,}index.html || true
      - name: Publish docs
        if: >
          github.event_name == 'push' && github.ref == 'refs/heads/main' &&
          matrix.os == 'ubuntu-latest' && matrix.nim == 'version-2-0'
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          build_dir: project/docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Set check-required on this
  success:
    needs: build
    if: always()
    runs-on: ubuntu-latest
    name: 'All check passes'
    steps:
      - if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        name: 'Fail when previous jobs fails'
        run: |
          echo "::error::One of the previous jobs failed"
          exit 1
